package fr.imag.mescal.gloudsim.gnuplot;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import fr.imag.mescal.gloudsim.util.FileControler;

/**
 * This class is used to analyze and reorganize the result generated by simulation.
 * the result file is to be generated at the end of simulation (see JobEmulator.java)
 * @author sdi
 *
 */
public class ExtractDataFromResult {
	
	public static void main(String[] args)
	{
		List<String> jobList = new ArrayList<String>();
		List<String> btList = new ArrayList<String>();
		
		String resultDir = "D:/INRIA-research/IEEE-13rd/experiment/bk-false-static-single-false-3600/bk-false-static-single-false-3600-4000-tr";
		//String resultDir = "E:/Java-project/CheckpointSim/gnuplot/bk-single-false-tr/bk-true-static-single-false-1000-arr-tr";
		String resultFileName = "result-false-static-single-false-3600-4000.txt";
		//String resultFileName = "result-true-static-single-false-1000-arr.txt";
		String resultFilePath = resultDir+"/"+resultFileName;
		String outputDir = resultDir+"/result";
		String outputJobFile = outputDir+"/job.txt";
		String outputBTFile = outputDir+"/bt.txt";
		List<String> lineList = FileControler.readFile(resultFilePath);
		Iterator<String> iter = lineList.iterator();
		for(int i=1,j=1;iter.hasNext();)
		{
			String line = iter.next().trim();
			if(line.startsWith("#"))
			{
				String[] data = line.split("\\s");
				String wclength = data[4];
				String ratio = data[5];
				//jobList.add(i+" "+wclength+" "+ratio);
				String jobID = data[0].substring(1);
				jobList.add(jobID+" "+wclength+" "+ratio);
				i++;
			}
			else
			{
				String[] data = line.split("\\s");
				String wclength = data[3];
				String ratio = data[4];
				//btList.add(j+" "+wclength+" "+ratio);
				String btID = data[0];
				btList.add(btID+" "+wclength+" "+ratio);
				j++;
			}
		}
		
		FileControler.print2File(jobList, outputJobFile);
		FileControler.print2File(btList, outputBTFile);
		System.out.println("done.");
	}
}
